package ud5_sesion4_ej13;
// Generated 29 nov 2022 20:32:47 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import ud5_sesion3.EmpleadoEntity;

/**
 * Departamentos generated by hbm2java
 */
@Entity
public class Departamentos {

	@Id
	private byte deptNo;
	private String dnombre;
	private String loc;
	@OneToMany(mappedBy="departamentos")
	private Set<Empleados> empleadoses = new HashSet<>();

	public Departamentos() {
	}

	public Departamentos(byte deptNo) {
		this.deptNo = deptNo;
	}

	public Departamentos(byte deptNo, String dnombre, String loc, Set empleadoses) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
		this.empleadoses = empleadoses;
	}

	public byte getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(byte deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
